components:
  schemas:
    pricing.v2.voice:
      properties:
        links:
          type: object
        name:
          type: string
        url:
          format: uri
          type: string
      type: object
    pricing.v2.voice.voice_country:
      properties:
        country:
          type: string
        iso_country:
          type: string
        url:
          format: uri
          type: string
      type: object
    pricing.v2.voice.voice_country|instance:
      properties:
        country:
          type: string
        inbound_call_prices:
          items:
            properties:
              base_price:
                type: number
              current_price:
                type: number
              number_type:
                type: string
            type: object
          type: array
        iso_country:
          type: string
        outbound_prefix_prices:
          items:
            properties:
              base_price:
                type: number
              current_price:
                type: number
              destination_prefixes:
                items:
                  type: string
                type: array
              friendly_name:
                type: string
              origination_prefixes:
                items:
                  type: string
                type: array
            type: object
          type: array
        price_unit:
          type: string
        url:
          format: uri
          type: string
      type: object
    pricing.v2.voice.voice_number:
      properties:
        country:
          type: string
        destination_number:
          type: string
        inbound_call_price:
          properties:
            base_price:
              type: number
            current_price:
              type: number
            number_type:
              type: string
          type: object
        iso_country:
          type: string
        origination_number:
          type: string
        outbound_call_prices:
          items:
            properties:
              base_price:
                type: number
              current_price:
                type: number
              origination_prefixes:
                items:
                  type: string
                type: array
            type: object
          type: array
        price_unit:
          type: string
        url:
          format: uri
          type: string
      type: object
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: https://support.twilio.com
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.twilio.com/legal/tos
  title: Twilio - Pricing
  version: 5.12.0
openapi: 3.0.1
paths:
  /v2/Voice/Countries:
    description: Voice pricing by country
    get:
      description: ''
      parameters:
      - description: How many resources to return in each list page. The default is
          50, and the maximum is 1000.
        in: query
        name: PageSize
        schema:
          maximum: 1000
          minimum: 1
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                properties:
                  countries:
                    items:
                      $ref: '#/components/schemas/pricing.v2.voice.voice_country'
                    type: array
                  meta:
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      key:
                        type: string
                      next_page_url:
                        format: uri
                        type: string
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type: string
                      url:
                        format: uri
                        type: string
                    type: object
                type: object
          description: OK
      security:
      - accountSid_authToken: []
      tags:
      - GA
    servers:
    - url: https://pricing.twilio.com
    x-default-output-properties: &id001
    - country
    - price_unit
    x-path-type: list
  /v2/Voice/Countries/{IsoCountry}:
    description: Voice pricing by country
    get:
      description: Fetch a specific Country.
      parameters:
      - description: The [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
          of the origin-based voice pricing information to fetch.
        in: path
        name: IsoCountry
        required: true
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pricing.v2.voice.voice_country|instance'
          description: OK
      security:
      - accountSid_authToken: []
      tags:
      - GA
    servers:
    - url: https://pricing.twilio.com
    x-default-output-properties: *id001
    x-path-type: instance
  /v2/Voice/Numbers/{DestinationNumber}:
    description: Voice pricing for a specific phone number
    get:
      description: Fetch pricing information for a specific destination and, optionally,
        origination phone number.
      parameters:
      - description: The destination phone number, in [E.164](https://www.twilio.com/docs/glossary/what-e164)
          format, for which to fetch the origin-based voice pricing information. E.164
          format consists of a + followed by the country code and subscriber number.
        in: path
        name: DestinationNumber
        required: true
        schema:
          type: string
      - description: The origination phone number, in [E.164](https://www.twilio.com/docs/glossary/what-e164)
          format, for which to fetch the origin-based voice pricing information. E.164
          format consists of a + followed by the country code and subscriber number.
        in: query
        name: OriginationNumber
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pricing.v2.voice.voice_number'
          description: OK
      security:
      - accountSid_authToken: []
      tags:
      - GA
    servers:
    - url: https://pricing.twilio.com
    x-default-output-properties:
    - country
    - inbound_call_price
    - price_unit
    x-path-type: instance
tags:
- description: This product is Generally Available.
  name: GA
