components:
  schemas:
    pricing.v1.messaging:
      type: object
      properties:
        links:
          format: uri-map
          nullable: true
          type: object
        name:
          nullable: true
          type: string
        url:
          format: uri
          nullable: true
          type: string
    pricing.v1.messaging.messaging_country:
      type: object
      properties:
        country:
          description: The name of the country
          nullable: true
          type: string
        iso_country:
          description: The ISO country code
          format: iso-country-code
          nullable: true
          type: string
        url:
          description: The absolute URL of the resource
          format: uri
          nullable: true
          type: string
    pricing.v1.messaging.messaging_country-instance:
      type: object
      properties:
        country:
          description: The name of the country
          nullable: true
          type: string
        inbound_sms_prices:
          type: array
          items:
            format: inbound-sms-price
            properties:
              base_price:
                type: number
              current_price:
                type: number
              number_type:
                type: string
            type: object
          nullable: true
          description: The list of InboundPrice records
        iso_country:
          description: The ISO country code
          format: iso-country-code
          nullable: true
          type: string
        outbound_sms_prices:
          type: array
          items:
            format: outbound-sms-price
            properties:
              carrier:
                type: string
              mcc:
                type: string
              mnc:
                type: string
              prices:
                items:
                  properties:
                    base_price:
                      type: number
                    current_price:
                      type: number
                    number_type:
                      type: string
                  type: object
                type: array
            type: object
          nullable: true
          description: The list of OutboundSMSPrice records
        price_unit:
          description: The currency in which prices are measured, in ISO 4127 format
            (e.g. usd, eur, jpy)
          format: currency
          nullable: true
          type: string
        url:
          description: The absolute URL of the resource
          format: uri
          nullable: true
          type: string
    pricing.v1.phone_number:
      type: object
      properties:
        links:
          format: uri-map
          nullable: true
          type: object
        name:
          nullable: true
          type: string
        url:
          format: uri
          nullable: true
          type: string
    pricing.v1.phone_number.phone_number_country:
      type: object
      properties:
        country:
          description: The name of the country
          nullable: true
          type: string
        iso_country:
          description: 'The ISO country code '
          format: iso-country-code
          nullable: true
          type: string
        url:
          description: The absolute URL of the resource
          format: uri
          nullable: true
          type: string
    pricing.v1.phone_number.phone_number_country-instance:
      type: object
      properties:
        country:
          description: The name of the country
          nullable: true
          type: string
        iso_country:
          description: 'The ISO country code '
          format: iso-country-code
          nullable: true
          type: string
        phone_number_prices:
          type: array
          items:
            format: phone-number-price
            properties:
              base_price:
                type: number
              current_price:
                type: number
              number_type:
                type: string
            type: object
          nullable: true
          description: The list of PhoneNumberPrices records
        price_unit:
          description: The currency in which prices are measured, in ISO 4127 format
            (e.g. usd, eur, jpy)
          format: currency
          nullable: true
          type: string
        url:
          description: The absolute URL of the resource
          format: uri
          nullable: true
          type: string
    pricing.v1.voice:
      type: object
      properties:
        links:
          format: uri-map
          nullable: true
          type: object
        name:
          nullable: true
          type: string
        url:
          format: uri
          nullable: true
          type: string
    pricing.v1.voice.voice_country:
      type: object
      properties:
        country:
          description: The name of the country
          nullable: true
          type: string
        iso_country:
          description: The ISO country code
          format: iso-country-code
          nullable: true
          type: string
        url:
          description: The absolute URL of the resource
          format: uri
          nullable: true
          type: string
    pricing.v1.voice.voice_country-instance:
      type: object
      properties:
        country:
          description: The name of the country
          nullable: true
          type: string
        inbound_call_prices:
          type: array
          items:
            format: inbound-call-price
            properties:
              base_price:
                type: number
              current_price:
                type: number
              number_type:
                type: string
            type: object
          nullable: true
          description: The list of InboundCallPrice records
        iso_country:
          description: The ISO country code
          format: iso-country-code
          nullable: true
          type: string
        outbound_prefix_prices:
          type: array
          items:
            format: outbound-prefix-price
            properties:
              base_price:
                type: number
              current_price:
                type: number
              friendly_name:
                type: string
              prefixes:
                items:
                  type: string
                type: array
            type: object
          nullable: true
          description: The list of OutboundPrefixPrice records
        price_unit:
          description: The currency in which prices are measured, in ISO 4127 format
            (e.g. usd, eur, jpy)
          format: currency
          nullable: true
          type: string
        url:
          description: The absolute URL of the resource
          format: uri
          nullable: true
          type: string
    pricing.v1.voice.voice_number:
      type: object
      properties:
        country:
          description: The name of the country
          nullable: true
          type: string
        inbound_call_price:
          description: The InboundCallPrice record
          format: inbound-call-price
          nullable: true
          properties:
            base_price:
              type: number
            current_price:
              type: number
            number_type:
              type: string
          type: object
        iso_country:
          description: The ISO country code
          format: iso-country-code
          nullable: true
          type: string
        number:
          description: The phone number
          format: phone-number
          nullable: true
          type: string
        outbound_call_price:
          description: The OutboundCallPrice record
          format: outbound-call-price
          nullable: true
          properties:
            base_price:
              type: number
            current_price:
              type: number
          type: object
        price_unit:
          description: The currency in which prices are measured, in ISO 4127 format
            (e.g. usd, eur, jpy)
          format: currency
          nullable: true
          type: string
        url:
          description: The absolute URL of the resource
          format: uri
          nullable: true
          type: string
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: https://support.twilio.com
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.twilio.com/legal/tos
  title: Twilio - Pricing
  version: 1.32.0
openapi: 3.0.1
paths:
  /v1/Messaging:
    servers:
    - url: https://pricing.twilio.com
    description: 'TODO: Resource-level docs'
    x-twilio:
      defaultOutputProperties:
      - name
      pathType: instance
  /v1/Messaging/Countries:
    servers:
    - url: https://pricing.twilio.com
    description: Messaging pricing by country
    x-twilio:
      defaultOutputProperties:
      - country
      - outbound_sms_prices
      - inbound_sms_prices
      - price_unit
      pathType: list
      parent: /Messaging
    get:
      description: ''
      operationId: ListMessagingCountry
      parameters:
      - description: How many resources to return in each list page. The default is
          50, and the maximum is 1000.
        in: query
        name: PageSize
        schema:
          maximum: 1000
          minimum: 1
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                title: ListMessagingCountryResponse
                properties:
                  countries:
                    type: array
                    items:
                      $ref: '#/components/schemas/pricing.v1.messaging.messaging_country'
                  meta:
                    type: object
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      next_page_url:
                        format: uri
                        type: string
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type: string
                      url:
                        format: uri
                        type: string
                      key:
                        type: string
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
  /v1/Messaging/Countries/{IsoCountry}:
    servers:
    - url: https://pricing.twilio.com
    description: Messaging pricing by country
    x-twilio:
      defaultOutputProperties:
      - country
      - outbound_sms_prices
      - inbound_sms_prices
      - price_unit
      pathType: instance
      parent: /Messaging
    get:
      description: ''
      operationId: FetchMessagingCountry
      parameters:
      - description: The [ISO country code](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
          of the pricing information to fetch.
        in: path
        name: IsoCountry
        required: true
        schema:
          format: iso-country-code
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pricing.v1.messaging.messaging_country-instance'
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
  /v1/PhoneNumbers:
    servers:
    - url: https://pricing.twilio.com
    description: 'TODO: Resource-level docs'
    x-twilio:
      defaultOutputProperties:
      - name
      pathType: list
  /v1/PhoneNumbers/Countries:
    servers:
    - url: https://pricing.twilio.com
    description: Phone number pricing by country
    x-twilio:
      defaultOutputProperties:
      - country
      - price_unit
      pathType: list
      parent: /PhoneNumbers
    get:
      description: ''
      operationId: ListPhoneNumberCountry
      parameters:
      - description: How many resources to return in each list page. The default is
          50, and the maximum is 1000.
        in: query
        name: PageSize
        schema:
          maximum: 1000
          minimum: 1
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                title: ListPhoneNumberCountryResponse
                properties:
                  countries:
                    type: array
                    items:
                      $ref: '#/components/schemas/pricing.v1.phone_number.phone_number_country'
                  meta:
                    type: object
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      next_page_url:
                        format: uri
                        type: string
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type: string
                      url:
                        format: uri
                        type: string
                      key:
                        type: string
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
  /v1/PhoneNumbers/Countries/{IsoCountry}:
    servers:
    - url: https://pricing.twilio.com
    description: Phone number pricing by country
    x-twilio:
      defaultOutputProperties:
      - country
      - price_unit
      pathType: instance
      parent: /PhoneNumbers
    get:
      description: ''
      operationId: FetchPhoneNumberCountry
      parameters:
      - description: The [ISO country code](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
          of the pricing information to fetch.
        in: path
        name: IsoCountry
        required: true
        schema:
          format: iso-country-code
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pricing.v1.phone_number.phone_number_country-instance'
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
  /v1/Voice:
    servers:
    - url: https://pricing.twilio.com
    description: 'TODO: Resource-level docs'
    x-twilio:
      defaultOutputProperties:
      - name
      pathType: instance
  /v1/Voice/Countries:
    servers:
    - url: https://pricing.twilio.com
    description: Voice pricing by country
    x-twilio:
      defaultOutputProperties:
      - country
      - price_unit
      pathType: list
      parent: /Voice
    get:
      description: ''
      operationId: ListVoiceCountry
      parameters:
      - description: How many resources to return in each list page. The default is
          50, and the maximum is 1000.
        in: query
        name: PageSize
        schema:
          maximum: 1000
          minimum: 1
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                title: ListVoiceCountryResponse
                properties:
                  countries:
                    type: array
                    items:
                      $ref: '#/components/schemas/pricing.v1.voice.voice_country'
                  meta:
                    type: object
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      next_page_url:
                        format: uri
                        type: string
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type: string
                      url:
                        format: uri
                        type: string
                      key:
                        type: string
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
  /v1/Voice/Countries/{IsoCountry}:
    servers:
    - url: https://pricing.twilio.com
    description: Voice pricing by country
    x-twilio:
      defaultOutputProperties:
      - country
      - price_unit
      pathType: instance
      parent: /Voice
    get:
      description: ''
      operationId: FetchVoiceCountry
      parameters:
      - description: The [ISO country code](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
          of the pricing information to fetch.
        in: path
        name: IsoCountry
        required: true
        schema:
          format: iso-country-code
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pricing.v1.voice.voice_country-instance'
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
  /v1/Voice/Numbers/{Number}:
    servers:
    - url: https://pricing.twilio.com
    description: Voice pricing for a specific phone number
    x-twilio:
      defaultOutputProperties:
      - country
      - outbound_call_price
      - inbound_call_price
      - price_unit
      pathType: instance
      parent: /Voice
    get:
      description: ''
      operationId: FetchVoiceNumber
      parameters:
      - description: The phone number to fetch.
        in: path
        name: Number
        required: true
        schema:
          format: phone-number
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pricing.v1.voice.voice_number'
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
  /v1/Voice/Numbers:
    servers:
    - url: https://pricing.twilio.com
    description: Voice pricing for a specific phone number
    x-twilio:
      defaultOutputProperties:
      - country
      - outbound_call_price
      - inbound_call_price
      - price_unit
      pathType: list
      parent: /Voice
servers:
- url: https://pricing.twilio.com
x-maturity:
- name: GA
  description: This product is Generally Available.
