components:
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
  schemas:
    content.v1.content.approval_create:
      type: object
      properties:
        name:
          type: string
          nullable: true
        category:
          type: string
          nullable: true
        content_type:
          type: string
          nullable: true
        status:
          type: string
          nullable: true
        rejection_reason:
          type: string
          nullable: true
        allow_category_change:
          type: boolean
          nullable: true
    content.v1.content.approval_fetch:
      type: object
      properties:
        sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^HX[0-9a-fA-F]{32}$
          nullable: true
          description: The unique string that that we created to identify the Content
            resource.
        account_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the [Account](https://www.twilio.com/docs/usage/api/account)
            that created Content resource.
        whatsapp:
          nullable: true
          description: Contains the whatsapp approval information for the Content
            resource, with fields such as approval status, rejection reason, and category,
            amongst others.
        url:
          type: string
          format: uri
          nullable: true
          description: The URL of the resource, relative to `https://content.twilio.com`.
    content.v1.content:
      type: object
      properties:
        date_created:
          type: string
          format: date-time
          nullable: true
          description: The date and time in GMT that the resource was created specified
            in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
        date_updated:
          type: string
          format: date-time
          nullable: true
          description: The date and time in GMT that the resource was last updated
            specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
        sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^HX[0-9a-fA-F]{32}$
          nullable: true
          description: The unique string that that we created to identify the Content
            resource.
        account_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the [Account](https://www.twilio.com/docs/usage/api/account)
            that created Content resource.
        friendly_name:
          type: string
          nullable: true
          description: A string name used to describe the Content resource. Not visible
            to the end recipient.
        language:
          type: string
          nullable: true
          description: Two-letter (ISO 639-1) language code (e.g., en) identifying
            the language the Content resource is in.
        variables:
          nullable: true
          description: 'Defines the default placeholder values for variables included
            in the Content resource. e.g. {"1": "Customer_Name"}.'
        types:
          nullable: true
          description: The [Content types](https://www.twilio.com/docs/content/content-types-overview)
            (e.g. twilio/text) for this Content resource.
        url:
          type: string
          format: uri
          nullable: true
          description: The URL of the resource, relative to `https://content.twilio.com`.
        links:
          type: object
          format: uri-map
          nullable: true
          description: A list of links related to the Content resource, such as approval_fetch
            and approval_create
    content.v1.content_and_approvals:
      type: object
      properties:
        date_created:
          type: string
          format: date-time
          nullable: true
          description: The date and time in GMT that the resource was created specified
            in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
        date_updated:
          type: string
          format: date-time
          nullable: true
          description: The date and time in GMT that the resource was last updated
            specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
        sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^HX[0-9a-fA-F]{32}$
          nullable: true
          description: The unique string that that we created to identify the Content
            resource.
        account_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the [Account](https://www.twilio.com/docs/usage/api/account)
            that created Content resource.
        friendly_name:
          type: string
          nullable: true
          description: A string name used to describe the Content resource. Not visible
            to the end recipient.
        language:
          type: string
          nullable: true
          description: Two-letter (ISO 639-1) language code (e.g., en) identifying
            the language the Content resource is in.
        variables:
          nullable: true
          description: 'Defines the default placeholder values for variables included
            in the Content resource. e.g. {"1": "Customer_Name"}.'
        types:
          nullable: true
          description: The [Content types](https://www.twilio.com/docs/content/content-types-overview)
            (e.g. twilio/text) for this Content resource.
        approval_requests:
          nullable: true
          description: The submitted information and approval request status of the
            Content resource.
    content.v1.legacy_content:
      type: object
      properties:
        date_created:
          type: string
          format: date-time
          nullable: true
          description: The date and time in GMT that the resource was created specified
            in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
        date_updated:
          type: string
          format: date-time
          nullable: true
          description: The date and time in GMT that the resource was last updated
            specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
        sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^HX[0-9a-fA-F]{32}$
          nullable: true
          description: The unique string that that we created to identify the Content
            resource.
        account_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the [Account](https://www.twilio.com/docs/usage/api/account)
            that created Content resource.
        friendly_name:
          type: string
          nullable: true
          description: A string name used to describe the Content resource. Not visible
            to the end recipient.
        language:
          type: string
          nullable: true
          description: Two-letter (ISO 639-1) language code (e.g., en) identifying
            the language the Content resource is in.
        variables:
          nullable: true
          description: 'Defines the default placeholder values for variables included
            in the Content resource. e.g. {"1": "Customer_Name"}.'
        types:
          nullable: true
          description: The [Content types](https://www.twilio.com/docs/content/content-types-overview)
            (e.g. twilio/text) for this Content resource.
        legacy_template_name:
          type: string
          nullable: true
          description: The string name of the legacy content template associated with
            this Content resource, unique across all template names for its account.  Only
            lowercase letters, numbers and underscores are allowed
        legacy_body:
          type: string
          nullable: true
          description: The string body field of the legacy content template associated
            with this Content resource
        url:
          type: string
          format: uri
          nullable: true
          description: The URL of the resource, relative to `https://content.twilio.com`.
info:
  title: Twilio - Content
  description: This is the public Twilio REST API.
  termsOfService: https://www.twilio.com/legal/tos
  contact:
    name: Twilio Support
    url: https://support.twilio.com
    email: support@twilio.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
openapi: 3.0.1
paths:
  /v1/Content/{Sid}/ApprovalRequests/whatsapp:
    servers:
    - url: https://content.twilio.com
    description: ''
    x-twilio:
      defaultOutputProperties:
      - sid
      - account_sid
      - whatsapp
      parent: /Content/{Sid}
      mountName: approval_create
      pathType: list
    post:
      description: ''
      tags:
      - ContentV1ApprovalCreate
      parameters:
      - name: Sid
        in: path
        description: ''
        schema:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^HX[0-9a-fA-F]{32}$
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/content.v1.content.approval_create'
              examples:
                createApproval:
                  value:
                    name: tree_fiddy
                    category: ACCOUNT_UPDATE
                    content_type: twilio/location
                    status: unsubmitted
                    rejection_reason: ''
                    allow_category_change: true
          headers:
            Access-Control-Allow-Origin:
              description: Specify the origin(s) allowed to access the resource
              schema:
                type: string
              example: '*'
            Access-Control-Allow-Methods:
              description: Specify the HTTP methods allowed when accessing the resource
              schema:
                type: string
              example: POST, OPTIONS
            Access-Control-Allow-Headers:
              description: Specify the headers allowed when accessing the resource
              schema:
                type: string
              example: Content-Type, Authorization
            Access-Control-Allow-Credentials:
              description: Indicates whether the browser should include credentials
              schema:
                type: boolean
            Access-Control-Expose-Headers:
              description: Headers exposed to the client
              schema:
                type: string
                example: X-Custom-Header1, X-Custom-Header2
          description: Created
      security:
      - accountSid_authToken: []
      operationId: CreateApprovalCreate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: CreateApprovalCreateRequest
              properties: {}
  /v1/Content/{Sid}/ApprovalRequests:
    servers:
    - url: https://content.twilio.com
    description: An Approval Fetch resource represents the approval status of a Content
      resource.
    x-twilio:
      defaultOutputProperties:
      - sid
      - account_sid
      - whatsapp
      parent: /Content/{Sid}
      mountName: approval_fetch
      pathType: instance
    get:
      description: Fetch a Content resource's approval status by its unique Content
        Sid
      tags:
      - ContentV1ApprovalFetch
      parameters:
      - name: Sid
        in: path
        description: The Twilio-provided string that uniquely identifies the Content
          resource whose approval information to fetch.
        schema:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^HX[0-9a-fA-F]{32}$
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/content.v1.content.approval_fetch'
              examples:
                getApproval:
                  value:
                    sid: HXaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    account_sid: ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    whatsapp:
                      type: whatsapp
                      name: tree_fiddy
                      category: ACCOUNT_UPDATE
                      content_type: twilio/location
                      status: approved
                      rejection_reason: ''
                      allow_category_change: true
                    url: https://content.twilio.com/v1/Content/HXaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/ApprovalRequests
          headers:
            Access-Control-Allow-Origin:
              description: Specify the origin(s) allowed to access the resource
              schema:
                type: string
              example: '*'
            Access-Control-Allow-Methods:
              description: Specify the HTTP methods allowed when accessing the resource
              schema:
                type: string
              example: POST, OPTIONS
            Access-Control-Allow-Headers:
              description: Specify the headers allowed when accessing the resource
              schema:
                type: string
              example: Content-Type, Authorization
            Access-Control-Allow-Credentials:
              description: Indicates whether the browser should include credentials
              schema:
                type: boolean
            Access-Control-Expose-Headers:
              description: Headers exposed to the client
              schema:
                type: string
                example: X-Custom-Header1, X-Custom-Header2
          description: OK
      security:
      - accountSid_authToken: []
      operationId: FetchApprovalFetch
servers:
- url: https://content.twilio.com
tags:
- name: ContentV1ApprovalCreate
- name: ContentV1ApprovalFetch
- name: ContentV1Content
- name: ContentV1ContentAndApprovals
- name: ContentV1LegacyContent
security:
- accountSid_authToken: []
