components:
  schemas:
    lookups.v1.phone_number:
      type: object
      properties:
        add_ons:
          nullable: true
          description: A JSON string with the results of the Add-ons you specified
        caller_name:
          nullable: true
          description: The name of the phone number's owner
        carrier:
          nullable: true
          description: The telecom company that provides the phone number
        country_code:
          description: The ISO country code for the phone number
          nullable: true
          type: string
        national_format:
          description: The phone number, in national format
          nullable: true
          type: string
        phone_number:
          description: The phone number in E.164 format
          format: phone-number
          nullable: true
          type: string
        url:
          description: The absolute URL of the resource
          format: uri
          nullable: true
          type: string
    phone_number_enum_type:
      enum:
      - landline
      - mobile
      - voip
      type: string
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: https://support.twilio.com
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.twilio.com/legal/tos
  title: Twilio - Lookups
  version: 1.32.0
openapi: 3.0.1
paths:
  /v1/PhoneNumbers/{PhoneNumber}:
    servers:
    - url: https://lookups.twilio.com
    description: Detailed information on phone numbers
    x-twilio:
      defaultOutputProperties:
      - caller_name
      - country_code
      - carrier
      pathType: instance
    get:
      description: ''
      operationId: FetchPhoneNumber
      parameters:
      - description: The phone number to lookup in [E.164](https://www.twilio.com/docs/glossary/what-e164)
          format, which consists of a + followed by the country code and subscriber
          number.
        in: path
        name: PhoneNumber
        required: true
        schema:
          format: phone-number
          type: string
      - description: The [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
          of the phone number to fetch. This is used to specify the country when the
          phone number is provided in a national format.
        in: query
        name: CountryCode
        schema:
          type: string
      - description: 'The type of information to return. Can be: `carrier` or `caller-name`.
          The default is null.  Carrier information costs $0.005 per phone number
          looked up.  Caller Name information is currently available only in the US
          and costs $0.01 per phone number looked up.  To retrieve both types on information,
          specify this parameter twice; once with `carrier` and once with `caller-name`
          as the value.'
        in: query
        name: Type
        schema:
          type: array
          items:
            type: string
      - description: The `unique_name` of an Add-on you would like to invoke. Can
          be the `unique_name` of an Add-on that is installed on your account. You
          can specify multiple instances of this parameter to invoke multiple Add-ons.
          For more information about  Add-ons, see the [Add-ons documentation](https://www.twilio.com/docs/add-ons).
        in: query
        name: AddOns
        schema:
          type: array
          items:
            type: string
      - description: Data specific to the add-on you would like to invoke. The content
          and format of this value depends on the add-on.
        in: query
        name: AddOnsData
        schema:
          type: object
          format: prefixed-collapsible-map-AddOns
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lookups.v1.phone_number'
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
servers:
- url: https://lookups.twilio.com
x-maturity:
- name: GA
  description: This product is Generally Available.
