components:
  schemas:
    pricing.v2.trunking_country:
      type: object
      properties:
        country:
          description: The name of the country
          nullable: true
          type: string
        iso_country:
          description: The ISO country code
          format: iso-country-code
          nullable: true
          type: string
        url:
          description: The absolute URL of the resource
          format: uri
          nullable: true
          type: string
    pricing.v2.trunking_country-instance:
      type: object
      properties:
        country:
          description: The name of the country
          nullable: true
          type: string
        iso_country:
          description: The ISO country code
          format: iso-country-code
          nullable: true
          type: string
        originating_call_prices:
          type: array
          items:
            format: inbound-call-price
            properties:
              base_price:
                type: number
              current_price:
                type: number
              number_type:
                type: string
            type: object
          nullable: true
          description: The list of OriginatingCallPrice records
        price_unit:
          description: The currency in which prices are measured, in ISO 4127 format
            (e.g. usd, eur, jpy)
          format: currency
          nullable: true
          type: string
        terminating_prefix_prices:
          type: array
          items:
            format: outbound-prefix-price-with-origin
            properties:
              base_price:
                type: number
              current_price:
                type: number
              destination_prefixes:
                items:
                  type: string
                type: array
              friendly_name:
                type: string
              origination_prefixes:
                items:
                  type: string
                type: array
            type: object
          nullable: true
          description: The list of TerminatingPrefixPrice records
        url:
          description: The absolute URL of the resource
          format: uri
          nullable: true
          type: string
    pricing.v2.trunking_number:
      type: object
      properties:
        country:
          description: The name of the country
          nullable: true
          type: string
        destination_number:
          description: The destination phone number, in E.164 format
          format: phone-number
          nullable: true
          type: string
        iso_country:
          description: The ISO country code
          format: iso-country-code
          nullable: true
          type: string
        originating_call_price:
          description: The OriginatingCallPrice record
          format: inbound-call-price
          nullable: true
          properties:
            base_price:
              type: number
            current_price:
              type: number
            number_type:
              type: string
          type: object
        origination_number:
          description: The origination phone number, in E.164 format
          format: phone-number
          nullable: true
          type: string
        price_unit:
          description: The currency in which prices are measured, in ISO 4127 format
            (e.g. usd, eur, jpy)
          format: currency
          nullable: true
          type: string
        terminating_prefix_prices:
          type: array
          items:
            format: outbound-prefix-price-with-origin
            properties:
              base_price:
                type: number
              current_price:
                type: number
              destination_prefixes:
                items:
                  type: string
                type: array
              friendly_name:
                type: string
              origination_prefixes:
                items:
                  type: string
                type: array
            type: object
          nullable: true
        url:
          description: The absolute URL of the resource
          format: uri
          nullable: true
          type: string
    pricing.v2.voice:
      type: object
      properties:
        links:
          description: The URLs of the related Countries and Numbers resources
          format: uri-map
          nullable: true
          type: object
        name:
          description: The resource name
          nullable: true
          type: string
        url:
          description: The absolute URL of the resource
          format: uri
          nullable: true
          type: string
    pricing.v2.voice.voice_country:
      type: object
      properties:
        country:
          description: The name of the country
          nullable: true
          type: string
        iso_country:
          description: The ISO country code
          format: iso-country-code
          nullable: true
          type: string
        url:
          description: The absolute URL of the resource
          format: uri
          nullable: true
          type: string
    pricing.v2.voice.voice_country-instance:
      type: object
      properties:
        country:
          description: The name of the country
          nullable: true
          type: string
        inbound_call_prices:
          type: array
          items:
            format: inbound-call-price
            properties:
              base_price:
                type: number
              current_price:
                type: number
              number_type:
                type: string
            type: object
          nullable: true
          description: The list of InboundCallPrice records
        iso_country:
          description: The ISO country code
          format: iso-country-code
          nullable: true
          type: string
        outbound_prefix_prices:
          type: array
          items:
            format: outbound-prefix-price-with-origin
            properties:
              base_price:
                type: number
              current_price:
                type: number
              destination_prefixes:
                items:
                  type: string
                type: array
              friendly_name:
                type: string
              origination_prefixes:
                items:
                  type: string
                type: array
            type: object
          nullable: true
          description: The list of OutboundPrefixPriceWithOrigin records
        price_unit:
          description: The currency in which prices are measured, in ISO 4127 format
            (e.g. usd, eur, jpy)
          format: currency
          nullable: true
          type: string
        url:
          description: The absolute URL of the resource
          format: uri
          nullable: true
          type: string
    pricing.v2.voice.voice_number:
      type: object
      properties:
        country:
          description: The name of the country
          nullable: true
          type: string
        destination_number:
          description: The destination phone number, in E.164 format
          format: phone-number
          nullable: true
          type: string
        inbound_call_price:
          description: The InboundCallPrice record
          format: inbound-call-price
          nullable: true
          properties:
            base_price:
              type: number
            current_price:
              type: number
            number_type:
              type: string
          type: object
        iso_country:
          description: The ISO country code
          format: iso-country-code
          nullable: true
          type: string
        origination_number:
          description: The origination phone number, in E.164 format
          format: phone-number
          nullable: true
          type: string
        outbound_call_prices:
          type: array
          items:
            format: outbound-call-price-with-origin
            properties:
              base_price:
                type: number
              current_price:
                type: number
              origination_prefixes:
                items:
                  type: string
                type: array
            type: object
          nullable: true
          description: The list of OutboundCallPriceWithOrigin records
        price_unit:
          description: The currency in which prices are measured, in ISO 4127 format
            (e.g. usd, eur, jpy)
          format: currency
          nullable: true
          type: string
        url:
          description: The absolute URL of the resource
          format: uri
          nullable: true
          type: string
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: https://support.twilio.com
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.twilio.com/legal/tos
  title: Twilio - Pricing
  version: 1.32.0
openapi: 3.0.1
paths:
  /v2/Trunking/Countries:
    servers:
    - url: https://pricing.twilio.com
    description: Trunking pricing by country
    x-twilio:
      defaultOutputProperties:
      - country
      - price_unit
      pathType: list
    get:
      description: ''
      operationId: ListTrunkingCountry
      parameters:
      - description: How many resources to return in each list page. The default is
          50, and the maximum is 1000.
        in: query
        name: PageSize
        schema:
          maximum: 1000
          minimum: 1
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                title: ListTrunkingCountryResponse
                properties:
                  countries:
                    type: array
                    items:
                      $ref: '#/components/schemas/pricing.v2.trunking_country'
                  meta:
                    type: object
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      next_page_url:
                        format: uri
                        type: string
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type: string
                      url:
                        format: uri
                        type: string
                      key:
                        type: string
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
  /v2/Trunking/Countries/{IsoCountry}:
    servers:
    - url: https://pricing.twilio.com
    description: Trunking pricing by country
    x-twilio:
      defaultOutputProperties:
      - country
      - price_unit
      pathType: instance
    get:
      description: Fetch a specific Country.
      operationId: FetchTrunkingCountry
      parameters:
      - description: The [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
          of the origin-based voice pricing information to fetch.
        in: path
        name: IsoCountry
        required: true
        schema:
          format: iso-country-code
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pricing.v2.trunking_country-instance'
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
  /v2/Trunking/Numbers/{DestinationNumber}:
    servers:
    - url: https://pricing.twilio.com
    description: Trunking pricing for a specific phone number
    x-twilio:
      defaultOutputProperties:
      - country
      - inbound_call_price
      - price_unit
      pathType: instance
    get:
      description: Fetch pricing information for a specific destination and, optionally,
        origination phone number.
      operationId: FetchTrunkingNumber
      parameters:
      - description: The destination phone number, in [E.164](https://www.twilio.com/docs/glossary/what-e164)
          format, for which to fetch the origin-based voice pricing information. E.164
          format consists of a + followed by the country code and subscriber number.
        in: path
        name: DestinationNumber
        required: true
        schema:
          format: phone-number
          type: string
      - description: The origination phone number, in [E.164](https://www.twilio.com/docs/glossary/what-e164)
          format, for which to fetch the origin-based voice pricing information. E.164
          format consists of a + followed by the country code and subscriber number.
        in: query
        name: OriginationNumber
        schema:
          format: phone-number
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pricing.v2.trunking_number'
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
  /v2/Trunking/Numbers:
    servers:
    - url: https://pricing.twilio.com
    description: Trunking pricing for a specific phone number
    x-twilio:
      defaultOutputProperties:
      - country
      - inbound_call_price
      - price_unit
      pathType: list
  /v2/Voice:
    servers:
    - url: https://pricing.twilio.com
    description: Voice pricing
    x-twilio:
      defaultOutputProperties:
      - name
      pathType: instance
  /v2/Voice/Countries:
    servers:
    - url: https://pricing.twilio.com
    description: Voice pricing by country
    x-twilio:
      defaultOutputProperties:
      - country
      - price_unit
      pathType: list
      parent: /Voice
    get:
      description: ''
      operationId: ListVoiceCountry
      parameters:
      - description: How many resources to return in each list page. The default is
          50, and the maximum is 1000.
        in: query
        name: PageSize
        schema:
          maximum: 1000
          minimum: 1
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                title: ListVoiceCountryResponse
                properties:
                  countries:
                    type: array
                    items:
                      $ref: '#/components/schemas/pricing.v2.voice.voice_country'
                  meta:
                    type: object
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      next_page_url:
                        format: uri
                        type: string
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type: string
                      url:
                        format: uri
                        type: string
                      key:
                        type: string
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
  /v2/Voice/Countries/{IsoCountry}:
    servers:
    - url: https://pricing.twilio.com
    description: Voice pricing by country
    x-twilio:
      defaultOutputProperties:
      - country
      - price_unit
      pathType: instance
      parent: /Voice
    get:
      description: Fetch a specific Country.
      operationId: FetchVoiceCountry
      parameters:
      - description: The [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
          of the origin-based voice pricing information to fetch.
        in: path
        name: IsoCountry
        required: true
        schema:
          format: iso-country-code
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pricing.v2.voice.voice_country-instance'
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
  /v2/Voice/Numbers/{DestinationNumber}:
    servers:
    - url: https://pricing.twilio.com
    description: Voice pricing for a specific phone number
    x-twilio:
      defaultOutputProperties:
      - country
      - inbound_call_price
      - price_unit
      pathType: instance
      parent: /Voice
    get:
      description: Fetch pricing information for a specific destination and, optionally,
        origination phone number.
      operationId: FetchVoiceNumber
      parameters:
      - description: The destination phone number, in [E.164](https://www.twilio.com/docs/glossary/what-e164)
          format, for which to fetch the origin-based voice pricing information. E.164
          format consists of a + followed by the country code and subscriber number.
        in: path
        name: DestinationNumber
        required: true
        schema:
          format: phone-number
          type: string
      - description: The origination phone number, in [E.164](https://www.twilio.com/docs/glossary/what-e164)
          format, for which to fetch the origin-based voice pricing information. E.164
          format consists of a + followed by the country code and subscriber number.
        in: query
        name: OriginationNumber
        schema:
          format: phone-number
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pricing.v2.voice.voice_number'
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
  /v2/Voice/Numbers:
    servers:
    - url: https://pricing.twilio.com
    description: Voice pricing for a specific phone number
    x-twilio:
      defaultOutputProperties:
      - country
      - inbound_call_price
      - price_unit
      pathType: list
      parent: /Voice
servers:
- url: https://pricing.twilio.com
x-maturity:
- name: GA
  description: This product is Generally Available.
