components:
  schemas:
    fax.v1.fax:
      properties:
        account_sid:
          maxLength: 34
          minLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          type: string
        api_version:
          type: string
        date_created:
          format: date-time
          type: string
        date_updated:
          format: date-time
          type: string
        direction:
          enum:
          - inbound
          - outbound
          type: string
        duration:
          nullable: true
          type: integer
        from:
          type: string
        links:
          type: object
        media_sid:
          maxLength: 34
          minLength: 34
          pattern: ^ME[0-9a-fA-F]{32}$
          type: string
        media_url:
          type: string
        num_pages:
          nullable: true
          type: integer
        price:
          type: number
        price_unit:
          type: string
        quality:
          enum:
          - standard
          - fine
          - superfine
          type: string
        sid:
          maxLength: 34
          minLength: 34
          pattern: ^FX[0-9a-fA-F]{32}$
          type: string
        status:
          enum:
          - queued
          - processing
          - sending
          - delivered
          - receiving
          - received
          - no-answer
          - busy
          - failed
          - canceled
          type: string
        to:
          type: string
        url:
          format: uri
          type: string
      type: object
    fax.v1.fax.fax_media:
      properties:
        account_sid:
          maxLength: 34
          minLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          type: string
        content_type:
          type: string
        date_created:
          format: date-time
          type: string
        date_updated:
          format: date-time
          type: string
        fax_sid:
          maxLength: 34
          minLength: 34
          pattern: ^FX[0-9a-fA-F]{32}$
          type: string
        sid:
          maxLength: 34
          minLength: 34
          pattern: ^ME[0-9a-fA-F]{32}$
          type: string
        url:
          format: uri
          type: string
      type: object
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: https://support.twilio.com
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.twilio.com/legal/tos
  title: Twilio - Fax
  version: 1.3.0
openapi: 3.0.1
paths:
  /v1/Faxes:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all faxes.
      parameters:
      - description: Retrieve only those faxes sent from this phone number, specified
          in [E.164](https://www.twilio.com/docs/glossary/what-e164) format.
        in: query
        name: From
        schema:
          type: string
      - description: Retrieve only those faxes sent to this phone number, specified
          in [E.164](https://www.twilio.com/docs/glossary/what-e164) format.
        in: query
        name: To
        schema:
          type: string
      - description: Retrieve only those faxes with a `date_created` that is before
          or equal to this value, specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
          format.
        in: query
        name: DateCreatedOnOrBefore
        schema:
          format: date-time
          type: string
      - description: Retrieve only those faxes with a `date_created` that is later
          than this value, specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
          format.
        in: query
        name: DateCreatedAfter
        schema:
          format: date-time
          type: string
      - description: How many resources to return in each list page. The default is
          50, and the maximum is 1000.
        in: query
        name: PageSize
        schema:
          maximum: 1000
          minimum: 1
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                properties:
                  faxes:
                    items:
                      $ref: '#/components/schemas/fax.v1.fax'
                    type: array
                  meta:
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      key:
                        type: string
                      next_page_url:
                        format: uri
                        type: string
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type: string
                      url:
                        format: uri
                        type: string
                    type: object
                type: object
          description: OK
      security:
      - accountSid_authToken: []
      tags:
      - Beta
    post:
      description: Create a new fax to send to a phone number or SIP endpoint.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                From:
                  description: The number the fax was sent from. Can be the phone
                    number in [E.164](https://www.twilio.com/docs/glossary/what-e164)
                    format or the SIP `from` value. The caller ID displayed to the
                    recipient uses this value. If this is a phone number, it must
                    be a Twilio number or a verified outgoing caller id from your
                    account. If `to` is a SIP address, this can be any alphanumeric
                    string (and also the characters `+`, `_`, `.`, and `-`), which
                    will be used in the `from` header of the SIP request.
                  type: string
                MediaUrl:
                  description: The URL of the PDF that contains the fax. See our [security](https://www.twilio.com/docs/usage/security)
                    page for information on how to ensure the request for your media
                    comes from Twilio.
                  format: uri
                  type: string
                Quality:
                  description: 'The [Fax Quality value](https://www.twilio.com/docs/fax/api/fax-resource#fax-quality-values)
                    that describes the fax quality. Can be: `standard`, `fine`, or
                    `superfine` and defaults to `fine`.'
                  enum:
                  - standard
                  - fine
                  - superfine
                  type: string
                SipAuthPassword:
                  description: The password to use with `sip_auth_username` to authenticate
                    faxes sent to a SIP address.
                  type: string
                SipAuthUsername:
                  description: The username to use with the `sip_auth_password` to
                    authenticate faxes sent to a SIP address.
                  type: string
                StatusCallback:
                  description: The URL we should call using the `POST` method to send
                    [status information](https://www.twilio.com/docs/fax/api/fax-resource#fax-status-callback)
                    to your application when the status of the fax changes.
                  format: uri
                  type: string
                StoreMedia:
                  description: 'Whether to store a copy of the sent media on our servers
                    for later retrieval. Can be: `true` or `false` and the default
                    is `true`.'
                  type: boolean
                To:
                  description: The phone number to receive the fax in [E.164](https://www.twilio.com/docs/glossary/what-e164)
                    format or the recipient's SIP URI.
                  type: string
                Ttl:
                  description: How long in minutes from when the fax is initiated
                    that we should try to send the fax.
                  type: integer
              required:
              - To
              - MediaUrl
              type: object
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fax.v1.fax'
          description: Created
      security:
      - accountSid_authToken: []
      tags:
      - Beta
    servers:
    - url: https://fax.twilio.com
    x-default-output-properties: &id002
    - sid
    - from
    - to
    - status
    - date_created
    x-path-type: list
  /v1/Faxes/{FaxSid}/Media:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all fax media instances for the specified fax.
      parameters:
      - description: The SID of the fax with the FaxMedia resources to read.
        in: path
        name: FaxSid
        required: true
        schema:
          maxLength: 34
          minLength: 34
          pattern: ^FX[0-9a-fA-F]{32}$
          type: string
      - description: How many resources to return in each list page. The default is
          50, and the maximum is 1000.
        in: query
        name: PageSize
        schema:
          maximum: 1000
          minimum: 1
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                properties:
                  media:
                    items:
                      $ref: '#/components/schemas/fax.v1.fax.fax_media'
                    type: array
                  meta:
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      key:
                        type: string
                      next_page_url:
                        format: uri
                        type: string
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type: string
                      url:
                        format: uri
                        type: string
                    type: object
                type: object
          description: OK
      security:
      - accountSid_authToken: []
      tags:
      - Beta
    servers:
    - url: https://fax.twilio.com
    x-default-output-properties: &id001
    - content_type
    - url
    x-path-type: list
  /v1/Faxes/{FaxSid}/Media/{Sid}:
    delete:
      description: Delete a specific fax media instance.
      parameters:
      - description: The SID of the fax with the FaxMedia resource to delete.
        in: path
        name: FaxSid
        required: true
        schema:
          maxLength: 34
          minLength: 34
          pattern: ^FX[0-9a-fA-F]{32}$
          type: string
      - description: The Twilio-provided string that uniquely identifies the FaxMedia
          resource to delete.
        in: path
        name: Sid
        required: true
        schema:
          maxLength: 34
          minLength: 34
          pattern: ^ME[0-9a-fA-F]{32}$
          type: string
      responses:
        204:
          description: The resource was deleted successfully.
      security:
      - accountSid_authToken: []
      tags:
      - Beta
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific fax media instance.
      parameters:
      - description: The SID of the fax with the FaxMedia resource to fetch.
        in: path
        name: FaxSid
        required: true
        schema:
          maxLength: 34
          minLength: 34
          pattern: ^FX[0-9a-fA-F]{32}$
          type: string
      - description: The Twilio-provided string that uniquely identifies the FaxMedia
          resource to fetch.
        in: path
        name: Sid
        required: true
        schema:
          maxLength: 34
          minLength: 34
          pattern: ^ME[0-9a-fA-F]{32}$
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fax.v1.fax.fax_media'
          description: OK
      security:
      - accountSid_authToken: []
      tags:
      - Beta
    servers:
    - url: https://fax.twilio.com
    x-default-output-properties: *id001
    x-path-type: instance
  /v1/Faxes/{Sid}:
    delete:
      description: Delete a specific fax and its associated media.
      parameters:
      - description: The Twilio-provided string that uniquely identifies the Fax resource
          to delete.
        in: path
        name: Sid
        required: true
        schema:
          maxLength: 34
          minLength: 34
          pattern: ^FX[0-9a-fA-F]{32}$
          type: string
      responses:
        204:
          description: The resource was deleted successfully.
      security:
      - accountSid_authToken: []
      tags:
      - Beta
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific fax.
      parameters:
      - description: The Twilio-provided string that uniquely identifies the Fax resource
          to fetch.
        in: path
        name: Sid
        required: true
        schema:
          maxLength: 34
          minLength: 34
          pattern: ^FX[0-9a-fA-F]{32}$
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fax.v1.fax'
          description: OK
      security:
      - accountSid_authToken: []
      tags:
      - Beta
    post:
      description: Update a specific fax.
      parameters:
      - description: The Twilio-provided string that uniquely identifies the Fax resource
          to update.
        in: path
        name: Sid
        required: true
        schema:
          maxLength: 34
          minLength: 34
          pattern: ^FX[0-9a-fA-F]{32}$
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                Status:
                  description: The new [status](https://www.twilio.com/docs/fax/api/fax-resource#fax-status-values)
                    of the resource. Can be only `canceled`. This may fail if transmission
                    has already started.
                  enum:
                  - canceled
                  type: string
              type: object
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fax.v1.fax'
          description: OK
      security:
      - accountSid_authToken: []
      tags:
      - Beta
    servers:
    - url: https://fax.twilio.com
    x-default-output-properties: *id002
    x-path-type: instance
tags:
- description: PLEASE NOTE that this is a Beta product that is subject to change.
    Use it with caution.
  name: Beta
