components:
  schemas:
    frontline.v1.user:
      properties:
        avatar:
          description: The avatar URL which will be shown in Frontline application
          nullable: true
          type: string
        friendly_name:
          description: The string that you assigned to describe the User
          nullable: true
          type: string
        identity:
          description: The string that identifies the resource's User
          nullable: true
          type: string
        is_available:
          description: Whether the User is available for new conversations
          nullable: true
          type: boolean
        sid:
          description: The unique string that identifies the resource
          maxLength: 34
          minLength: 34
          nullable: true
          pattern: ^US[0-9a-fA-F]{32}$
          type: string
        state:
          description: Current state of this user
          enum:
          - active
          - deactivated
          nullable: true
          type: string
        url:
          description: An absolute URL for this user.
          format: uri
          nullable: true
          type: string
      type: object
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: https://support.twilio.com
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.twilio.com/legal/tos
  title: Twilio - Frontline
  version: 1.30.0
openapi: 3.0.1
paths:
  /v1/Users/{Sid}:
    description: A User resource represents a frontline user.
    get:
      description: Fetch a frontline user
      operationId: FetchUser
      parameters:
      - description: The SID of the User resource to fetch. This value can be either
          the `sid` or the `identity` of the User resource to fetch.
        in: path
        name: Sid
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/frontline.v1.user'
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - Beta
    post:
      description: Update an existing frontline user
      operationId: UpdateUser
      parameters:
      - description: The SID of the User resource to update. This value can be either
          the `sid` or the `identity` of the User resource to update.
        in: path
        name: Sid
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                FriendlyName:
                  description: The string that you assigned to describe the User.
                  type: string
                Avatar:
                  description: The avatar URL which will be shown in Frontline application.
                  type: string
                State:
                  description: Current state of this user. Can be either `active`
                    or `deactivated`.
                  enum:
                  - active
                  - deactivated
                  type: string
                IsAvailable:
                  description: Whether the User is available for new conversations.
                    Set to `false` to prevent User from receiving new inbound conversations
                    if you are using [Pool Routing](https://www.twilio.com/docs/frontline/handle-incoming-conversations#3-pool-routing).
                  type: boolean
              title: UpdateUserRequest
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/frontline.v1.user'
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - Beta
    servers:
    - url: https://frontline-api.twilio.com
    x-twilio:
      defaultOutputProperties:
      - sid
      - identity
      pathType: instance
servers:
- url: https://frontline-api.twilio.com
x-maturity:
- description: PLEASE NOTE that this is a Beta product that is subject to change.
    Use it with caution.
  name: Beta
