components:
  schemas:
    lookups.v2.phone_number:
      type: object
      properties:
        call_forwarding:
          nullable: true
          description: An object that contains call forwarding status information
        caller_name:
          nullable: true
          description: An object that contains caller name information
        calling_country_code:
          description: International dialing prefix
          nullable: true
          type: string
        country_code:
          description: Phone number's ISO country code
          nullable: true
          type: string
        line_type_intelligence:
          nullable: true
          description: An object that contains line type information
        live_activity:
          nullable: true
          description: An object that contains live activity information
        national_format:
          description: Phone number in national format
          nullable: true
          type: string
        phone_number:
          description: Phone number in E.164 format
          format: phone-number
          nullable: true
          type: string
        sim_swap:
          nullable: true
          description: An object that contains SIM swap information
        url:
          description: The absolute URL of the resource
          format: uri
          nullable: true
          type: string
        valid:
          description: Boolean which indicates if the phone number is valid
          nullable: true
          type: boolean
        validation_errors:
          type: array
          items:
            type: string
            $ref: '#/components/schemas/phone_number_enum_validation_error'
          nullable: true
          description: Contains reasons why a phone number is invalid
    phone_number_enum_type:
      enum:
      - landline
      - mobile
      - voip
      type: string
    phone_number_enum_validation_error:
      enum:
      - TOO_SHORT
      - TOO_LONG
      - INVALID_BUT_POSSIBLE
      - INVALID_COUNTRY_CODE
      - INVALID_LENGTH
      - NOT_A_NUMBER
      type: string
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: https://support.twilio.com
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.twilio.com/legal/tos
  title: Twilio - Lookups
  version: 1.32.0
openapi: 3.0.1
paths:
  /v2/PhoneNumbers/{PhoneNumber}:
    servers:
    - url: https://lookups.twilio.com
    description: Query information on a phone number so that you can make a trusted
      interaction with your user
    x-twilio:
      defaultOutputProperties:
      - calling_country_code
      - phone_number
      - country_code
      - valid
      - validation_results
      - national_format
      pathType: instance
    get:
      description: ''
      operationId: FetchPhoneNumber
      parameters:
      - description: The phone number to lookup in E.164 or national format. Default
          country code is +1 (North America).
        in: path
        name: PhoneNumber
        required: true
        schema:
          type: string
      - description: A comma-separated list of fields to return. Possible values are
          caller_name, sim_swap, call_forwarding, live_activity, line_type_intelligence.
        in: query
        name: Fields
        schema:
          type: string
      - description: The [country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
          used if the phone number provided is in national format.
        in: query
        name: CountryCode
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lookups.v2.phone_number'
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - Beta
servers:
- url: https://lookups.twilio.com
x-maturity:
- name: Beta
  description: PLEASE NOTE that this is a Beta product that is subject to change.
    Use it with caution.
