components:
  schemas:
    chat.v3.channel:
      type: object
      properties:
        account_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the Account that created the resource
        attributes:
          description: The JSON string that stores application-specific data
          nullable: true
          type: string
        created_by:
          description: The identity of the User that created the channel
          nullable: true
          type: string
        date_created:
          type: string
          format: date-time
          nullable: true
          description: The ISO 8601 date and time in GMT when the resource was created
        date_updated:
          type: string
          format: date-time
          nullable: true
          description: The ISO 8601 date and time in GMT when the resource was last
            updated
        friendly_name:
          description: The string that you assigned to describe the resource
          nullable: true
          type: string
        members_count:
          description: The number of Members in the Channel
          nullable: true
          type: integer
        messages_count:
          description: The number of Messages that have been passed in the Channel
          nullable: true
          type: integer
        messaging_service_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^MG[0-9a-fA-F]{32}$
          nullable: true
          description: The unique ID of the Messaging Service this channel belongs
            to.
        service_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^IS[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the Service that the resource is associated with
        sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^CH[0-9a-fA-F]{32}$
          nullable: true
          description: The unique string that identifies the resource
        type:
          type: string
          $ref: '#/components/schemas/channel_enum_channel_type'
          nullable: true
          description: 'The visibility of the channel. Can be: `public` or `private`'
        unique_name:
          description: An application-defined string that uniquely identifies the
            resource
          nullable: true
          type: string
        url:
          description: The absolute URL of the Channel resource
          format: uri
          nullable: true
          type: string
    channel_enum_channel_type:
      enum:
      - public
      - private
      type: string
    channel_enum_webhook_enabled_type:
      enum:
      - 'true'
      - 'false'
      type: string
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: https://support.twilio.com
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.twilio.com/legal/tos
  title: Twilio - Chat
  version: 1.32.0
openapi: 3.0.1
paths:
  /v3/Services/{ServiceSid}/Channels/{Sid}:
    servers:
    - url: https://chat.twilio.com
    description: A Channel resource represents a chat/conversation channel with an
      ordered list of messages and a participant roster.
    x-twilio:
      defaultOutputProperties:
      - sid
      - unique_name
      - friendly_name
      pathType: instance
    post:
      description: Update a specific Channel.
      operationId: UpdateChannel
      parameters:
      - description: The unique SID identifier of the Service.
        in: path
        name: ServiceSid
        required: true
        schema:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^IS[0-9a-fA-F]{32}$
      - description: A 34 character string that uniquely identifies this Channel.
        in: path
        name: Sid
        required: true
        schema:
          type: string
      - description: The X-Twilio-Webhook-Enabled HTTP request header
        in: header
        name: X-Twilio-Webhook-Enabled
        schema:
          type: string
          $ref: '#/components/schemas/channel_enum_webhook_enabled_type'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                Type:
                  type: string
                  $ref: '#/components/schemas/channel_enum_channel_type'
                  description: TThe Type for this Channel to migrate to. Can only
                    be `private`. Migration to 'public' is not allowed.
                MessagingServiceSid:
                  type: string
                  minLength: 34
                  maxLength: 34
                  pattern: ^MG[0-9a-fA-F]{32}$
                  description: The unique ID of the [Messaging Service](https://www.twilio.com/docs/sms/services/api)
                    this channel belongs to.
              title: UpdateChannelRequest
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/chat.v3.channel'
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
  /v3/Services/{ServiceSid}/Channels:
    servers:
    - url: https://chat.twilio.com
    description: A Channel resource represents a chat/conversation channel with an
      ordered list of messages and a participant roster.
    x-twilio:
      defaultOutputProperties:
      - sid
      - unique_name
      - friendly_name
      pathType: list
servers:
- url: https://chat.twilio.com
x-maturity:
- name: GA
  description: This product is Generally Available.
