components:
  schemas:
    monitor.v1.alert:
      type: object
      properties:
        account_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the Account that created the resource
        alert_text:
          description: The text of the alert
          nullable: true
          type: string
        api_version:
          description: The API version used when the alert was generated
          nullable: true
          type: string
        date_created:
          type: string
          format: date-time
          nullable: true
          description: The ISO 8601 date and time in GMT when the resource was created
        date_generated:
          type: string
          format: date-time
          nullable: true
          description: The date and time when the alert was generated specified in
            ISO 8601 format
        date_updated:
          type: string
          format: date-time
          nullable: true
          description: The ISO 8601 date and time in GMT when the resource was last
            updated
        error_code:
          description: The error code for the condition that generated the alert
          nullable: true
          type: string
        log_level:
          description: The log level
          nullable: true
          type: string
        more_info:
          description: The URL of the page in our Error Dictionary with more information
            about the error condition
          nullable: true
          type: string
        request_method:
          description: The method used by the request that generated the alert
          enum:
          - HEAD
          - GET
          - POST
          - PATCH
          - PUT
          - DELETE
          format: http-method
          nullable: true
          type: string
        request_url:
          description: The URL of the request that generated the alert
          format: uri
          nullable: true
          type: string
        resource_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^[a-zA-Z]{2}[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the resource for which the alert was generated
        service_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^[a-zA-Z]{2}[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the service or resource that generated the alert
        sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^NO[0-9a-fA-F]{32}$
          nullable: true
          description: The unique string that identifies the resource
        url:
          description: The absolute URL of the Alert resource
          format: uri
          nullable: true
          type: string
    monitor.v1.alert-instance:
      type: object
      properties:
        account_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the Account that created the resource
        alert_text:
          description: The text of the alert
          nullable: true
          type: string
        api_version:
          description: The API version used when the alert was generated
          nullable: true
          type: string
        date_created:
          type: string
          format: date-time
          nullable: true
          description: The ISO 8601 date and time in GMT when the resource was created
        date_generated:
          type: string
          format: date-time
          nullable: true
          description: The date and time when the alert was generated specified in
            ISO 8601 format
        date_updated:
          type: string
          format: date-time
          nullable: true
          description: The ISO 8601 date and time in GMT when the resource was last
            updated
        error_code:
          description: The error code for the condition that generated the alert
          nullable: true
          type: string
        log_level:
          description: The log level
          nullable: true
          type: string
        more_info:
          description: The URL of the page in our Error Dictionary with more information
            about the error condition
          nullable: true
          type: string
        request_headers:
          description: The request headers of the request that generated the alert
          nullable: true
          type: string
        request_method:
          description: The method used by the request that generated the alert
          enum:
          - HEAD
          - GET
          - POST
          - PATCH
          - PUT
          - DELETE
          format: http-method
          nullable: true
          type: string
        request_url:
          description: The URL of the request that generated the alert
          format: uri
          nullable: true
          type: string
        request_variables:
          description: The variables passed in the request that generated the alert
          nullable: true
          type: string
        resource_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^[a-zA-Z]{2}[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the resource for which the alert was generated
        response_body:
          description: The response body of the request that generated the alert
          nullable: true
          type: string
        response_headers:
          description: The response headers of the request that generated the alert
          nullable: true
          type: string
        service_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^[a-zA-Z]{2}[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the service or resource that generated the alert
        sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^NO[0-9a-fA-F]{32}$
          nullable: true
          description: The unique string that identifies the resource
        url:
          description: The absolute URL of the Alert resource
          format: uri
          nullable: true
          type: string
    monitor.v1.event:
      type: object
      properties:
        account_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the Account that created the resource
        actor_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^US[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the actor that caused the event, if available
        actor_type:
          description: The type of actor that caused the event
          nullable: true
          type: string
        description:
          description: A description of the event
          nullable: true
          type: string
        event_data:
          nullable: true
          description: A JSON string that represents an object with additional data
            about the event
        event_date:
          type: string
          format: date-time
          nullable: true
          description: The ISO 8601 date and time in GMT when the event was recorded
        event_type:
          description: The event's type
          nullable: true
          type: string
        links:
          description: The absolute URLs of related resources
          format: uri-map
          nullable: true
          type: object
        resource_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^[a-zA-Z]{2}[0-9a-fA-F]{32}$
          nullable: true
          description: The SID of the resource that was affected
        resource_type:
          description: The type of resource that was affected
          nullable: true
          type: string
        sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^AE[0-9a-fA-F]{32}$
          nullable: true
          description: The unique string that identifies the resource
        source:
          description: The originating system or interface that caused the event
          nullable: true
          type: string
        source_ip_address:
          description: The IP address of the source
          nullable: true
          type: string
        url:
          description: The absolute URL of the resource that was affected
          format: uri
          nullable: true
          type: string
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: https://support.twilio.com
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.twilio.com/legal/tos
  title: Twilio - Monitor
  version: 1.32.0
openapi: 3.0.1
paths:
  /v1/Alerts/{Sid}:
    servers:
    - url: https://monitor.twilio.com
    description: Debugger alerts
    x-twilio:
      defaultOutputProperties:
      - sid
      - error_code
      - log_level
      - alert_text
      pathType: instance
    get:
      description: ''
      operationId: FetchAlert
      parameters:
      - description: The SID of the Alert resource to fetch.
        in: path
        name: Sid
        required: true
        schema:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^NO[0-9a-fA-F]{32}$
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/monitor.v1.alert-instance'
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
  /v1/Alerts:
    servers:
    - url: https://monitor.twilio.com
    description: Debugger alerts
    x-twilio:
      defaultOutputProperties:
      - sid
      - error_code
      - log_level
      - alert_text
      pathType: list
    get:
      description: ''
      operationId: ListAlert
      parameters:
      - description: 'Only show alerts for this log-level.  Can be: `error`, `warning`,
          `notice`, or `debug`.'
        in: query
        name: LogLevel
        schema:
          type: string
      - description: Only include alerts that occurred on or after this date and time.
          Specify the date and time in GMT and format as `YYYY-MM-DD` or `YYYY-MM-DDThh:mm:ssZ`.
          Queries for alerts older than 30 days are not supported.
        in: query
        name: StartDate
        schema:
          type: string
          format: date-time
      - description: Only include alerts that occurred on or before this date and
          time. Specify the date and time in GMT and format as `YYYY-MM-DD` or `YYYY-MM-DDThh:mm:ssZ`.
          Queries for alerts older than 30 days are not supported.
        in: query
        name: EndDate
        schema:
          type: string
          format: date-time
      - description: How many resources to return in each list page. The default is
          50, and the maximum is 1000.
        in: query
        name: PageSize
        schema:
          maximum: 1000
          minimum: 1
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                title: ListAlertResponse
                properties:
                  alerts:
                    type: array
                    items:
                      $ref: '#/components/schemas/monitor.v1.alert'
                  meta:
                    type: object
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      next_page_url:
                        format: uri
                        type: string
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type: string
                      url:
                        format: uri
                        type: string
                      key:
                        type: string
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
  /v1/Events/{Sid}:
    servers:
    - url: https://monitor.twilio.com
    description: Debugger events
    x-twilio:
      defaultOutputProperties:
      - sid
      - event_type
      - event_type
      - description
      pathType: instance
    get:
      description: ''
      operationId: FetchEvent
      parameters:
      - description: The SID of the Event resource to fetch.
        in: path
        name: Sid
        required: true
        schema:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^AE[0-9a-fA-F]{32}$
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/monitor.v1.event'
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
  /v1/Events:
    servers:
    - url: https://monitor.twilio.com
    description: Debugger events
    x-twilio:
      defaultOutputProperties:
      - sid
      - event_type
      - event_type
      - description
      pathType: list
    get:
      description: Returns a list of events in the account, sorted by event-date.
      operationId: ListEvent
      parameters:
      - description: Only include events initiated by this Actor. Useful for auditing
          actions taken by specific users or API credentials.
        in: query
        name: ActorSid
        schema:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^US[0-9a-fA-F]{32}$
      - description: Only include events of this [Event Type](https://www.twilio.com/docs/usage/monitor-events#event-types).
        in: query
        name: EventType
        schema:
          type: string
      - description: Only include events that refer to this resource. Useful for discovering
          the history of a specific resource.
        in: query
        name: ResourceSid
        schema:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^[a-zA-Z]{2}[0-9a-fA-F]{32}$
      - description: Only include events that originated from this IP address. Useful
          for tracking suspicious activity originating from the API or the Twilio
          Console.
        in: query
        name: SourceIpAddress
        schema:
          type: string
      - description: Only include events that occurred on or after this date. Specify
          the date in GMT and [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        in: query
        name: StartDate
        schema:
          type: string
          format: date-time
      - description: Only include events that occurred on or before this date. Specify
          the date in GMT and [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        in: query
        name: EndDate
        schema:
          type: string
          format: date-time
      - description: How many resources to return in each list page. The default is
          50, and the maximum is 1000.
        in: query
        name: PageSize
        schema:
          maximum: 1000
          minimum: 1
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                title: ListEventResponse
                properties:
                  events:
                    type: array
                    items:
                      $ref: '#/components/schemas/monitor.v1.event'
                  meta:
                    type: object
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      next_page_url:
                        format: uri
                        type: string
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type: string
                      url:
                        format: uri
                        type: string
                      key:
                        type: string
          description: OK
      security:
      - accountSid_authToken: []
      x-maturity:
      - GA
servers:
- url: https://monitor.twilio.com
x-maturity:
- name: GA
  description: This product is Generally Available.
