components:
  schemas:
    monitor.v1.alert:
      properties:
        account_sid:
          maxLength: 34
          minLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          type: string
        alert_text:
          type: string
        api_version:
          type: string
        date_created:
          format: date-time
          type: string
        date_generated:
          format: date-time
          type: string
        date_updated:
          format: date-time
          type: string
        error_code:
          type: string
        log_level:
          type: string
        more_info:
          type: string
        request_method:
          enum:
          - head
          - get
          - post
          - patch
          - put
          - delete
          - HEAD
          - GET
          - POST
          - PATCH
          - PUT
          - DELETE
          type: string
        request_url:
          format: uri
          type: string
        resource_sid:
          maxLength: 34
          minLength: 34
          pattern: ^[a-zA-Z]{2}[0-9a-fA-F]{32}$
          type: string
        service_sid:
          maxLength: 34
          minLength: 34
          pattern: ^[a-zA-Z]{2}[0-9a-fA-F]{32}$
          type: string
        sid:
          maxLength: 34
          minLength: 34
          pattern: ^NO[0-9a-fA-F]{32}$
          type: string
        url:
          format: uri
          type: string
      type: object
    monitor.v1.alert|instance:
      properties:
        account_sid:
          maxLength: 34
          minLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          type: string
        alert_text:
          type: string
        api_version:
          type: string
        date_created:
          format: date-time
          type: string
        date_generated:
          format: date-time
          type: string
        date_updated:
          format: date-time
          type: string
        error_code:
          type: string
        log_level:
          type: string
        more_info:
          type: string
        request_headers:
          type: string
        request_method:
          enum:
          - head
          - get
          - post
          - patch
          - put
          - delete
          - HEAD
          - GET
          - POST
          - PATCH
          - PUT
          - DELETE
          type: string
        request_url:
          format: uri
          type: string
        request_variables:
          type: string
        resource_sid:
          maxLength: 34
          minLength: 34
          pattern: ^[a-zA-Z]{2}[0-9a-fA-F]{32}$
          type: string
        response_body:
          type: string
        response_headers:
          type: string
        service_sid:
          maxLength: 34
          minLength: 34
          pattern: ^[a-zA-Z]{2}[0-9a-fA-F]{32}$
          type: string
        sid:
          maxLength: 34
          minLength: 34
          pattern: ^NO[0-9a-fA-F]{32}$
          type: string
        url:
          format: uri
          type: string
      type: object
    monitor.v1.event:
      properties:
        account_sid:
          maxLength: 34
          minLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          type: string
        actor_sid:
          maxLength: 34
          minLength: 34
          pattern: ^US[0-9a-fA-F]{32}$
          type: string
        actor_type:
          type: string
        description:
          type: string
        event_data:
          type: object
        event_date:
          format: date-time
          type: string
        event_type:
          type: string
        links:
          type: object
        resource_sid:
          maxLength: 34
          minLength: 34
          pattern: ^[a-zA-Z]{2}[0-9a-fA-F]{32}$
          type: string
        resource_type:
          type: string
        sid:
          maxLength: 34
          minLength: 34
          pattern: ^AE[0-9a-fA-F]{32}$
          type: string
        source:
          type: string
        source_ip_address:
          type: string
        url:
          format: uri
          type: string
      type: object
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: https://support.twilio.com
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.twilio.com/legal/tos
  title: Twilio - Monitor
  version: 1.3.0
openapi: 3.0.1
paths:
  /v1/Alerts:
    description: Debugger alerts
    get:
      description: ''
      parameters:
      - description: 'Only show alerts for this log-level.  Can be: `error`, `warning`,
          `notice`, or `debug`.'
        in: query
        name: LogLevel
        schema:
          type: string
      - description: Only include alerts that occurred on or after this date and time.
          Specify the date and time in GMT and format as `YYYY-MM-DD` or `YYYY-MM-DDThh:mm:ssZ`.
          Queries for alerts older than 30 days are not supported.
        in: query
        name: StartDate
        schema:
          format: date-time
          type: string
      - description: Only include alerts that occurred on or before this date and
          time. Specify the date and time in GMT and format as `YYYY-MM-DD` or `YYYY-MM-DDThh:mm:ssZ`.
          Queries for alerts older than 30 days are not supported.
        in: query
        name: EndDate
        schema:
          format: date-time
          type: string
      - description: How many resources to return in each list page. The default is
          50, and the maximum is 1000.
        in: query
        name: PageSize
        schema:
          maximum: 1000
          minimum: 1
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                properties:
                  alerts:
                    items:
                      $ref: '#/components/schemas/monitor.v1.alert'
                    type: array
                  meta:
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      key:
                        type: string
                      next_page_url:
                        format: uri
                        type: string
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type: string
                      url:
                        format: uri
                        type: string
                    type: object
                type: object
          description: OK
      security:
      - accountSid_authToken: []
      tags:
      - GA
    servers:
    - url: https://monitor.twilio.com
    x-default-output-properties: &id001
    - sid
    - error_code
    - log_level
    - alert_text
    x-path-type: list
  /v1/Alerts/{Sid}:
    description: Debugger alerts
    get:
      description: ''
      parameters:
      - description: The SID of the Alert resource to fetch.
        in: path
        name: Sid
        required: true
        schema:
          maxLength: 34
          minLength: 34
          pattern: ^NO[0-9a-fA-F]{32}$
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/monitor.v1.alert|instance'
          description: OK
      security:
      - accountSid_authToken: []
      tags:
      - GA
    servers:
    - url: https://monitor.twilio.com
    x-default-output-properties: *id001
    x-path-type: instance
  /v1/Events:
    description: Debugger events
    get:
      description: Returns a list of events in the account, sorted by event-date.
      parameters:
      - description: Only include events initiated by this Actor. Useful for auditing
          actions taken by specific users or API credentials.
        in: query
        name: ActorSid
        schema:
          maxLength: 34
          minLength: 34
          pattern: ^US[0-9a-fA-F]{32}$
          type: string
      - description: Only include events of this [Event Type](https://www.twilio.com/docs/usage/monitor-events#event-types).
        in: query
        name: EventType
        schema:
          type: string
      - description: Only include events that refer to this resource. Useful for discovering
          the history of a specific resource.
        in: query
        name: ResourceSid
        schema:
          maxLength: 34
          minLength: 34
          pattern: ^[a-zA-Z]{2}[0-9a-fA-F]{32}$
          type: string
      - description: Only include events that originated from this IP address. Useful
          for tracking suspicious activity originating from the API or the Twilio
          Console.
        in: query
        name: SourceIpAddress
        schema:
          type: string
      - description: Only include events that occurred on or after this date. Specify
          the date in GMT and [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        in: query
        name: StartDate
        schema:
          format: date-time
          type: string
      - description: Only include events that occurred on or before this date. Specify
          the date in GMT and [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        in: query
        name: EndDate
        schema:
          format: date-time
          type: string
      - description: How many resources to return in each list page. The default is
          50, and the maximum is 1000.
        in: query
        name: PageSize
        schema:
          maximum: 1000
          minimum: 1
          type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                properties:
                  events:
                    items:
                      $ref: '#/components/schemas/monitor.v1.event'
                    type: array
                  meta:
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      key:
                        type: string
                      next_page_url:
                        format: uri
                        type: string
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type: string
                      url:
                        format: uri
                        type: string
                    type: object
                type: object
          description: OK
      security:
      - accountSid_authToken: []
      tags:
      - GA
    servers:
    - url: https://monitor.twilio.com
    x-default-output-properties: &id002
    - sid
    - event_type
    - event_type
    - description
    x-path-type: list
  /v1/Events/{Sid}:
    description: Debugger events
    get:
      description: ''
      parameters:
      - description: The SID of the Event resource to fetch.
        in: path
        name: Sid
        required: true
        schema:
          maxLength: 34
          minLength: 34
          pattern: ^AE[0-9a-fA-F]{32}$
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/monitor.v1.event'
          description: OK
      security:
      - accountSid_authToken: []
      tags:
      - GA
    servers:
    - url: https://monitor.twilio.com
    x-default-output-properties: *id002
    x-path-type: instance
tags:
- description: This product is Generally Available.
  name: GA
